### ISSUE TITLE
(Windows 7, 64bit) Font error, most of the material are unreadable

### ISSUE THREAD

**Issue by marcogaio** [gcompris/GCompris-qt#270] opened 2021-08-24 11:29 UTC
Just installed version 1.1 64bit on Windows7 64bit PC.

But most of the activities are unusable, and are unusable the configuration page too, because seems that GCmopris choose the wrong font.
Screenshot attached.
![Schermata da 2021-08-24 13-23-01](https://user-images.githubusercontent.com/7048664/130608736-3dad124b-7de6-42ce-8671-bdca83f5d0da.png)

Tried normal and 'Safe' mode, same behaviour.

Thanks.

**Comment by petitlapin** [comment] 2021-08-25 06:13
Hi,

can you please check in C:\Users\Johnny\AppData\Local\gcompris\GCompris.conf the value of "font" under [%General] section please? If it it not "Andika-R.otf", can you please set it to this: `font=Andika-R.otf` and run again GCompris (you need to update the file whiile GCompris is not running).

By default, we use a font that we ship so it should be available on all systems.

If it does not work, can you go in the GCompris configuration (once GCompris is started, the blue tool on the bottom). There is one button that corresponds to the font selection: https://lafibre.info/testdebit/linux/202005_gcompris_20.png ("Choisir la police" in the image). Can you check if changing it here is better?

**Comment by marcogaio** [comment] 2021-08-25 10:47
> can you please check in %LocalAppData%\gcompris\GCompris.conf (you can type this directly in the file explorer) the value of "font" under [%General] section please? If it it not "Andika-R.otf", can you please set it to this: `font=Andika-R.otf` and run again GCompris (you need to update the file whiile GCompris is not running).

I confirm, in configuration file font is `font=Andika-R.otf`.

> By default, we use a font that we ship so it should be available on all systems.

I've looked on disk, bu there's no `Andika-R.otf' font file anyware... I've tried to set a different font (eg, `Arial.ttf` or another `.otf` font in disk) but nothing changed.

> If it does not work, can you go in the GCompris configuration (once GCompris is started, the blue tool on the bottom). There is one button that corresponds to the font selection: https://lafibre.info/testdebit/linux/202005_gcompris_20.png ("Choisir la police" in the image). Can you check if changing it here is better?

This is the configuration screen i see...
![Schermata da 2021-08-25 12-34-54](https://user-images.githubusercontent.com/7048664/130777366-80ac8eba-3759-43c5-8b37-5d57fa5f3d62.png)
![Schermata da 2021-08-25 12-34-49](https://user-images.githubusercontent.com/7048664/130777367-f30d3c32-5818-4afc-bc5e-feb86ffe72ff.png)

**Comment by marcogaio** [comment] 2021-08-25 11:02
I've also tried 32bit version (on the same Win7 64bit machine), and also i've tried to enable `Add gcompris-qt to the system PATH for al users` install option; same behaviour.

**Comment by Animtim** [comment] 2021-08-25 11:26
This is very weird, first time someone reports this.

Can you try, in the Font selection panel ("Selezione dei caratteri" in your screenshot), to select any different font, and then close the configuration page either with Enter key or pressing the green button at the top to validate your changes. Maybe try a few different ones to be sure.

**Comment by marcogaio** [comment] 2021-08-25 12:24
It works!
![Schermata da 2021-08-25 14-19-36](https://user-images.githubusercontent.com/7048664/130789538-e791f129-5482-4ace-ac41-fca4800fb02a.png)

Not all fonts seems to work (eg, some other fonts behave like `Andika-R`) but most do.

In config file i got:
```
font=Arial
isCurrentFontEmbedded=false
```
where the original/startup file had:
```
font=Andika-R.otf
isCurrentFontEmbedded=true
```

**Comment by Animtim** [comment] 2021-08-25 13:27
Thanks for testing, good that it works with other fonts.

A wild guess is that it could be an issue with OTF fonts support on your system, either system-wide or specifically in GCompris.

As we didn't have other people reporting such issue (and I'm sure we have many other users using windows7), I would classify this as a local bug, unless more people report the same in the future.

**Comment by marcogaio** [comment] 2021-08-25 14:22
Three question/point:

1. this is a pretty standard Win7 Pro 64bit box, and i use some other OTF files. Could be a _local bug_, surely, but it is really strange...
2. font could be incompatible, but surely it is not present on disk... i don't know how on this box the installer does not install that font, but surely does not...
3. AFAI've understood, if gcompris does not find the font,  it takes the first font in list, in this box _Abaco_, that is effectively a symbol font. I think could be smarter...

I've tried to look for the installer log, to found if there's some error (_not copy font because..._) but i've not found it...

Thanks.

**Comment by marcogaio** [comment] 2021-08-25 14:30
I've just tried with a Win10 (20H2) 64bit box. Works as expected.

So seems at least a Win7 trouble...

**Comment by Animtim** [comment] 2021-08-25 14:52
Thanks for the investigation details.

The font is not copied as-is but, as for all the resources, is included inside an .rcc file, so it's normal that you can't find the file.

But I'm sure that at least it used to work on windows 7... I don't have anymore a windows7 system here to reproduce, maybe @petitlapin has one.

**Comment by marcogaio** [comment] 2021-08-25 15:23
> Thanks for the investigation details.

Thanks to you!
 
> The font is not copied as-is but, as for all the resources, is included inside an .rcc file, so it's normal that you can't find the file.

Ah! This explain also `isCurrentFontEmbedded=true`... ;-)

> But I'm sure that at least it used to work on windows 7... I don't have anymore a windows7 system here to reproduce, maybe @petitlapin has one.

OK, i'll wait for feedback... indeed, because Win7 is currently EOL, i think that a safe options would be also simply deprecate Win7 support...

**Comment by marcogaio** [comment] 2021-08-30 11:26
Done, screenshot with error attached.
![Schermata da 2021-08-30 13-25-43](https://user-images.githubusercontent.com/7048664/131332270-1bb37e29-b809-459f-9740-92dc6f53f66b.png)

**Comment by petitlapin** [comment] 2021-09-01 15:58
> OK, but if you remove `%LocalAppData%\gcompris\GCompris.conf` and rerun gcompris, what font get selected? Andika (embedded one) or Aharoni (the first non-embedded font, that in this case is a normal, non-symbol font)?

Andika.

Looking at the log you provided, it does not manage to load the Andika font. Can you try OpenDyslexic on your system? Both otf and ttf?
If both fail, it may be an issue with embedded fonts. If only otf fails, it may be an issue with otf on your system. If both works, I don't know :)

**Comment by marcogaio** [comment] 2021-09-02 11:24
> Looking at the log you provided, it does not manage to load the Andika font. Can you try OpenDyslexic on your system? Both otf and ttf?
> If both fail, it may be an issue with embedded fonts. If only otf fails, it may be an issue with otf on your system. If both works, I don't know :)

Only OpenDyslexic seems to work... screen attached.
![Schermata da 2021-09-02 13-15-16](https://user-images.githubusercontent.com/7048664/131835079-e87c2c55-85d8-4fe2-8406-3f58cc4a0a87.png)

> Also, can you install Andika on your system (from https://software.sil.org/andika/download/) and select this one too to double check if it comes from the font or the embed part?
Installed, i can see it on font control panel but not show up in GCompris font list...

Mah...

**Comment by petitlapin** [comment] 2021-09-06 18:59
We don't do anything special to get the system fonts (except excluding symbol fonts).
We ship both openDyslexicFonts so except the fact that one is ttf and the other is otf, I don't think we changed anything on them.

**Comment by marcogaio** [comment] 2021-09-07 10:51
Boh. It is really strange. Sorry but i don't know.

But on next year i've to complete the migration to Win10, so... i'll solve the problem anyway.

Thanks to all.

**Comment by petitlapin** [comment] 2022-08-08 09:44
Let's close this issue as there is a solution. Feel free to reopen if needed

**Closed by petitlapin** 2022-08-08 09:44 UTC

**Comment by sueahackerofficial** [comment] 2026-06-02 13:51
I know. It hasn't done me any good. It's because Windows 7 may not understand the encoding, the font or the system. You could reinstall GCompris.
Or we could do a little trick.
1) You will get Andika from [Google Fonts](https://fonts.google.com/specimen/Andika).
2) You will extract it to the GCompris folder and rename the Regular font file (usually Andika-Regular.ttf) to Andika-R.ttf.
3) Then remove the preinstalled Andika-R and replace it with that one.
4) Reload GCompris and change the font to **Andika-R.ttf**.
5) Now you will see GCompris in Andika.
If that doesn't work, why don't you reinstall GCompris, troubleshoot in cmd.exe or reinstall Windows?
It might be a problem with Windows.
If that didn't work try something else.
